background            #000000
foreground            #e2e2e2
cursor                #e2e2e2
color0                #010101
color8                #373737
color1                #b24f4f
color9                #df6565
color2                #97a044
color10               #c5d15c
color3                #ed9e56
color11               #ecce58
color4                #6f92b5
color12               #8cb6e1
color5                #a084ad
color13               #cfabdf
color6                #629c93
color14               #80cabf
color7                #a7a8a7
color15               #e2e2e2
selection_background  #ed9e56
selection_foreground  #000000

active_tab_foreground #ed9e56
active_tab_background #000000
inactive_tab_foreground #a7a8a7
inactive_tab_background #000000

active_border_color #8cb6e1
inactive_border_color #373737
