return {
	"SmiteshP/nvim-navic",
	event = "BufReadPre",
	opts = {
		icons = {
			Array = " ",
			Boolean = "󰨙 ",
			Class = "󰆼 ",
			Color = " ",
			Constant = "󰏿 ",
			Constructor = " ",
			Enum = " ",
			EnumMember = " ",
			Event = " ",
			Field = "󱈢 ",
			File = " ",
			Folder = " ",
			Function = "󰡱 ",
			Interface = "󱡠 ",
			Key = " ",
			Keyword = " ",
			Method = "󰡱 ",
			Module = " ",
			Namespace = "󰦮 ",
			Null = "󰟢 ",
			Number = "󰎠 ",
			Object = "󰮄 ",
			Operator = "󱓉 ",
			Package = "󰏗 ",
			Property = "󰖷 ",
			Reference = " ",
			Snippet = "󱄽 ",
			String = "󰅳 ",
			Struct = "󰆼 ",
			Text = "󰉿 ",
			TypeParameter = " ",
			Unit = " ",
			Value = "󰎠 ",
			Variable = "󰫧 ",
		},
		separator = " 🯟 ",
		lsp = {
			auto_attach = true,
		},
	},
}
