general {
    ignore_empty_input = true
}

background {
    path = screenshot
    blur_passes = 3
    blur_size = 5
}

animations {
    animation = fade, 1, 2, linear
}

input-field {
    monitor =
    fade_on_empty = false
}
