[main]
font=monospace:size=13
# font-bold=monospace:weight=semibold:size=14
# font-bold=monospace:weight=semibold:size=14
# font-bold-italic=monospace:weight=semibold:slant=italic:size=14
pad=0x0 center
include=~/.config/foot/themes/blackbg.ini

[colors-dark]
# alpha=0.9
# alpha-mode=matching

[scrollback]
lines=3000

[mouse]
hide-when-typing=yes

[key-bindings]
scrollback-up-page=Control+Alt+b
scrollback-down-page=Control+Alt+f
scrollback-up-half-page=Control+Alt+u
scrollback-down-half-page=Control+Alt+d
scrollback-up-line=Control+Alt+y
scrollback-down-line=Control+Alt+e
scrollback-home=Control+Alt+g
scrollback-end=Control+Shift+g
search-start=Control+Shift+slash
font-increase=Control+Shift+equal
font-decrease=Control+Shift+minus
font-reset=Control+Shift+0
spawn-terminal=Control+Shift+Return
pipe-command-output=[sh -c "f=$(mktemp) && cat - > $f; foot --title='command output' $EDITOR $f; rm $f"] Control+Alt+o
pipe-scrollback=[sh -c "f=$(mktemp) && cat - > $f; foot --title='scrollback' $EDITOR $f; rm $f"] Control+Alt+s
show-urls-launch=Control+Alt+l
show-urls-copy=Control+Shift+l
prompt-prev=Control+Alt+p
prompt-next=Control+Alt+n

[search-bindings]
find-prev=Control+p
find-next=Control+n
delete-prev-word=Control+Alt+w
scrollback-up-page=Control+Alt+b
scrollback-down-page=Control+Alt+f
scrollback-up-half-page=Control+Alt+u
scrollback-down-half-page=Control+Alt+d
scrollback-up-line=Control+Alt+y
scrollback-down-line=Control+Alt+e
scrollback-home=Control+Alt+g
scrollback-end=Control+Shift+g

# vim: commentstring=#\ %s
