[colors-dark]
foreground=afafaf
background=000000
cursor    =000000 29aa29
selection-foreground=9eafc0
selection-background=000088
# black
regular0  =000000
bright0   =555555
# red
regular1  =aa2929
bright1   =ff5555
# green
regular2  =29aa29
bright2   =55ff55
# yellow
regular3  =bb7722
bright3   =ffee50
# blue
regular4  =4949d0
bright4   =7070ff
# purple
regular5  =aa30aa
bright5   =ff55ff
# cyan
regular6  =30aaaa
bright6   =55ffff
# white
regular7  =afafaf
bright7   =ffffff
