[colors-dark]
foreground=deb88d
background=09141b
cursor    =08131a fca02f
selection-foreground=fee4ce
selection-background=1e4962
# black
regular0  =17384c
bright0   =434b53
# red
regular1  =d15123
bright1   =d48678
# green
regular2  =027c9b
bright2   =628d98
# yellow
regular3  =fca02f
bright3   =fdd39f
# blue
regular4  =23565f
bright4   =1bbcdd
# purple
regular5  =68d4f1
bright5   =bbe3ee
# cyan
regular6  =50a3b5
bright6   =87acb4
# white
regular7  =deb88d
bright7   =fee4ce
