local o = vim.o
local g = vim.g

o.mouse = ""
o.number = true
o.relativenumber = true
o.undofile = true
o.swapfile = false
o.updatetime = 2000
o.tabstop = 4 -- Tab size
o.shiftwidth = 0 -- Indent width (copy tabstop value)
o.expandtab = true -- Use spaces
o.shiftround = true -- Round indent to multiple of shiftwidth
o.autoindent = true -- Copy indent on new line
o.copyindent = true -- Also copy indent structure with autoindent
o.linebreak = true -- Wrap lines at word boundaries
o.showbreak = "󰘍 "
o.ignorecase = true
o.smartcase = true
o.signcolumn = "yes"
o.inccommand = "split"
o.scrolloff = 8
o.splitright = true
o.splitbelow = true
o.completeopt = "fuzzy,noinsert,menu,menuone,popup"
o.pumheight = 15
o.list = true
o.listchars = "leadtab:│ ,tab:<->,trail:-,multispace:∙,lead: ,nbsp:␣"
o.foldlevel = 99 -- Start with all folds open
o.virtualedit = "block" -- Better virtual-block mode
o.termguicolors = true -- Use 24-bit colors after :restart
-- o.guicursor = "a:block-Cursor" -- Always use block cursor with 'Cursor' hl-group

g.c_syntax_for_h = true -- Set filetype to c for header files
